---
- name: Add couchdb chart repo
  kubernetes.core.helm_repository:
    name: couchdb
    repo_url: "https://apache.github.io/couchdb-helm"

- name: Deploy couchdb chart on 4.2.0 with values loaded from template
  kubernetes.core.helm:
    release_name: ccc-db
    release_namespace: comp90024
    chart_ref: couchdb/couchdb
    chart_version: 4.2.0
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait: true