- name: Create/Update couchdb in cluster and auto setup couchdb cluster
  hosts: master_nodes
  run_once: true
  vars_files:
    - vars/couchdb_vars.yaml
  roles:
    - cluster_couchdb_setup
    - get_couchdb_credentials