---
- name: Create infrastructure resources on MRC
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars/openstack_vars.yaml
  roles:
    - create_openstack_security_group
    - create_openstack_key_pair
    - create_openstack_volume
    - create_openstack_instance

- name: Environment setup for each node
  hosts: all
  gather_facts: true
  vars_files:
    - vars/cluster_vars.yaml
  roles:
    - node_environment_setup

# - name: Install Kubernetes
#   hosts: all
#   roles:
#     - install_kubernetes

