- name: Environment setup for each node
  hosts: all
  gather_facts: true
  vars_files:
    - vars/instance_vars.yaml
  roles:
    - node_environment_setup

- name: Mount OpenStack volumes
  hosts: master_nodes, worker_nodes
  gather_facts: true
  vars_files:
    - vars/instance_vars.yaml
  roles:
    - node_volume_mount

- name: Patch kubespray files
  hosts: localhost
  roles:
    - patch_kubespary_hostname