mastodon_harvester_target:
  - name: "social"
    url: "https://mastodon.social"


ACCOUNT_MAIL: FILL_YOUR_ACCOUNT
ACCOUNT_PASSWORD: FILL_YOUR_PASSWORD
ACCOUNT_FILE: pytooter_clientcred.secret
DBCONFIG_ADDRESS: FILL_YOUR_ADDRESS
DBCONFIG_PORT: 5984
DBCONFIG_DB: mastodon
DB_USERNAME: FILL_DB_USERNAME
DB_PASSWORD: FILL_DB_PASSWORD
