---
# Download link, this vaule is configured by input when using start.sh Option8 
twitter_download_link: https://www.dropbox.com/s/r6l4ke6h858bzph/twitter-huge.json.zip

# Presistant volume claim size
PV_SIZE: 90Gi

# CouchDB in-cluster service URL
COUCHDB_HOST: ccc-db-svc-couchdb.comp90024.svc.cluster.local
COUCHDB_PORT: 5984
COUCHDB_DATABASE: tweet