server:
  port : 8080

couchdb:
  mastodon:
    host: ${MASTODON_COUCHDB_HOST:http://172.26.133.116}
    port: ${MASTODON_COUCHDB_PORT:31000}
    username: ${MASTODON_COUCHDB_USERNAME:admin}
    password: ${MASTODON_COUCHDB_PASSWORD:fM2ViRNmR3X6CLrXhe4X}
    mastodonDB: ${MASTODON_COUCHDB_MASTODONDB:mastodon}
  tweet:
    host: ${TWEET_COUCHDB_HOST:https://couchdb.quantumlab.cloud}
    port: ${TWEET_COUCHDB_PORT:443}
    sudoDB: ${TWEET_COUCHDB_SUDO:sudo}
    username: ${TWEET_COUCHDB_USERNAME:admin}
    password: ${TWEET_COUCHDB_PASSWORD:admin}
    tweetDB: ${TWEET_COUCHDB_TWEET:tweet_demo_2}

spring:

  #  swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #  swagger3


  profiles:
    active: docker

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  main:
    allow-circular-references: true