name: docker-build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push MH
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:Mastodon_Harvester"
          push: true
          tags: comp90024team65/mastodon-harvester:latest

      -
        name: Build and push TWITTER
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:tweet_docker"
          push: true
          tags: comp90024team65/tweet-handler:latest
